- name: Copy Docker image tar file
  copy:
    src: /path/to/myapp.tar
    dest: /tmp/myapp.tar

- name: Load Docker image
  shell: docker load < /tmp/myapp.tar

- name: Run container
  shell: docker run -d --name myapp -p 80:5000 krutika09/project05-ansible-cicd:v1

