- hosts: target
  become: true
  tasks:
    - name: Stop and remove existing container (if any)
      docker_container:
        name: myapp
        state: absent
        force_kill: true

    - name: Pull Docker image from DockerHub
      docker_image:
        name: krutika09/project05-ansible-cicd
        tag: v1
        source: pull

    - name: Run container from pulled image
      docker_container:
        name: myapp
        image: krutika09/project05-ansible-cicd:v1
        state: started
        ports:
          - "80:5000"

