---
- hosts: target
  become: yes
  tasks:
    - name: Stop and remove existing container (if any)
      shell: docker stop myapp || true && docker rm myapp || true


    - name: Pull image from DockerHub
      shell: docker pull krutika09/project05-ansible-cicd:v1


    - name: Run container from loaded image
      shell: docker run -d --name myapp -p 80:5000 krutika09/project05-ansible-cicd:v1

