---
- hosts: target
  become: yes
  tasks:
    - name: Stop existing container
      shell: docker stop myapp || true && docker rm myapp || true

    - name: Copy Docker image from Jenkins to remote
      synchronize:
        src: /var/lib/jenkins/workspace/ansible
        dest: /tmp/app

    - name: Load Docker image
      shell: docker load < /tmp/app/myapp.tar

    - name: Run container
      shell: docker run -d --name myapp -p 80:5000 myapp:v1

